### ISSUE TITLE
Uploading Firmware

### ISSUE THREAD

**Issue by alex03man** [daid/LegacyCura#1010]
Hello Daid,

Today I'm setting up octoprint on a dedicated linux machine and I'm trying to learn cura as well. I have one issue where if I try to install custom firmware it gets stuck on reading firmware and outputs this trace on the command line

Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/share/cura/Cura/gui/firmwareInstall.py", line 95, in OnRun
    hexFile = intelHex.readHex(self.filename)
  File "/usr/share/cura/Cura/avr_isp/intelHex.py", line 18, in readHex
    if line[0] != ':':
IndexError: string index out of range

Can you please give me some insight into what is going wrong here? I've followed all the directions and it still isnt working!

PS. when I installed cura your wiki says to "sudo ./package.sh debian_i386" and that failed for me over and over again, so I tried it without sudo and it worked. I'm using ubuntu 14.04 LTS btw.

**Comment by daid** [comment]
What kind of file are you trying to upload as firmware? You should be supplying a hex file.
