### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by jenschr** [daid/LegacyCura#107]
Hi Daid,
I have a model that fails to slice in RC2, but slices nicely in RC3. The model is here http://www.flashgamer.com/a/lid8_1b.stl and the dump is below. Please tell if I can help solving this in any way.

File C:\Users\gaming3\Dropbox\3d\lid8_1b.stl is being chain exported.
Carve procedure took 4 seconds.
Preface procedure took 1 second.
Inset procedure took 15 seconds.
Fill procedure took 36 seconds.
Multiply procedure took 1 second.
Speed procedure took 1 second.
Raft procedure took 26 seconds.
Skirt procedure took 1 second.
Traceback (most recent call last):
  File "app_main.py", line 51, in run_toplevel
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura.py", line 65, in <module>
    main()
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura.py", line 59, in main
    sliceRun.runSlice(args)
  File "C:\Program Files (x86)\Cura_RC2\Cura\util\sliceRun.py", line 51, in runSlice
    skeinforge_craft.writeOutput(fileName)
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\skeinforge_application\skeinforge_utilities\skeinforge_craft.py", line 135, in writeOutput
    return pluginModule.writeOutput(fileName, shouldAnalyze)
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\skeinforge_application\skeinforge_plugins\craft_plugins\export.py", line 275, in writeOutput
    gcodeText = skeinforge_craft.getChainTextFromProcedures(fileName, procedures[: -1], gcodeText)
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\skeinforge_application\skeinforge_utilities\skeinforge_craft.py", line 44, in getChainTextFromProcedures
    text = craftModule.getCraftedText(fileName, text)
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\skeinforge_application\skeinforge_plugins\craft_plugins\comb.py", line 61, in getCraftedText
    return getCraftedTextFromText(archive.getTextIfEmpty(fileName, text), repository)
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\skeinforge_application\skeinforge_plugins\craft_plugins\comb.py", line 71, in getCraftedTextFromText
    return CombSkein().getCraftedGcode(gcodeText, repository)
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\skeinforge_application\skeinforge_plugins\craft_plugins\comb.py", line 333, in getCraftedGcode
    self.parseLine(line)
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\skeinforge_application\skeinforge_plugins\craft_plugins\comb.py", line 452, in parseLine
    self.addIfTravel(splitLine)
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\skeinforge_application\skeinforge_plugins\craft_plugins\comb.py", line 204, in addIfTravel
    self.addGcodePathZ(self.travelFeedRateMinute, self.getAroundBetweenPath(self.oldLocation.dropAxis(), location.dropAxis()), highestZ)
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\skeinforge_application\skeinforge_plugins\craft_plugins\comb.py", line 248, in getAroundBetweenPath
    segment = boundarySegment.getSegment(boundarySegmentIndex, boundarySegments, self.edgeWidth, self.runningJumpSpace)
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\skeinforge_application\skeinforge_plugins\craft_plugins\comb.py", line 146, in getSegment
    end = getJumpPointIfInside(self.boundary, nextBegin, edgeWidth, runningJumpSpace)
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\skeinforge_application\skeinforge_plugins\craft_plugins\comb.py", line 101, in getJumpPointIfInside
    insetBoundary = intercircle.getSimplifiedInsetFromClockwiseLoop(boundary, -edgeWidth)
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\fabmetheus_utilities\intercircle.py", line 483, in getSimplifiedInsetFromClockwiseLoop
    return getWithoutIntersections(euclidean.getSimplifiedLoop(inset, radius))
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\fabmetheus_utilities\euclidean.py", line 1522, in getSimplifiedLoop
    loop = getHalfSimplifiedLoop( loop, simplificationRadius, 0 )
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\fabmetheus_utilities\euclidean.py", line 894, in getHalfSimplifiedLoop
    elif not isWithinChannel( channelRadius, pointIndex, loop ):
  File "C:\Program Files (x86)\Cura_RC2\Cura\cura_sf\fabmetheus_utilities\euclidean.py", line 1866, in isWithinChannel
    aheadSegmentComplex /= aheadSegmentComplexLength
ZeroDivisionError: <ZeroDivisionError object at 0x10dcd50c>

**Comment by daid** [comment]
This bug was solved in RC3. RC3 is newer then RC2.
