### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jenschr** [daid/LegacyCura#108]
I have a very basic file (http://www.flashgamer.com/a/calibration.stl) that I use to ensure that the print bed is level and that the x/y motors are pulling evenly. In RC3, this file won't slice with the following log/error:

File C:\Users\gaming3\Dropbox\3d\calibration.stl is being chain exported.
Carve procedure took 1 second.
Preface procedure took 0 seconds.
Inset procedure took 0 seconds.
Fill procedure took 0 seconds.
Speed procedure took 0 seconds.
Traceback (most recent call last):
  File "app_main.py", line 51, in run_toplevel
  File "C:\Program Files (x86)\Cura_RC3\Cura\cura.py", line 70, in <module>
    main()
  File "C:\Program Files (x86)\Cura_RC3\Cura\cura.py", line 64, in main
    sliceRun.runSlice(args)
  File "C:\Program Files (x86)\Cura_RC3\Cura\util\sliceRun.py", line 73, in runSlice
    skeinforge_craft.writeOutput(fileName)
  File "C:\Program Files (x86)\Cura_RC3\Cura\cura_sf\skeinforge_application\skeinforge_utilities\skeinforge_craft.py", line 135, in writeOutput
    return pluginModule.writeOutput(fileName, shouldAnalyze)
  File "C:\Program Files (x86)\Cura_RC3\Cura\cura_sf\skeinforge_application\skeinforge_plugins\craft_plugins\export.py", line 275, in writeOutput
    gcodeText = skeinforge_craft.getChainTextFromProcedures(fileName, procedures[: -1], gcodeText)
  File "C:\Program Files (x86)\Cura_RC3\Cura\cura_sf\skeinforge_application\skeinforge_utilities\skeinforge_craft.py", line 44, in getChainTextFromProcedures
    text = craftModule.getCraftedText(fileName, text)
  File "C:\Program Files (x86)\Cura_RC3\Cura\cura_sf\skeinforge_application\skeinforge_plugins\craft_plugins\raft.py", line 226, in getCraftedText
    return getCraftedTextFromText(archive.getTextIfEmpty(fileName, text), repository)
  File "C:\Program Files (x86)\Cura_RC3\Cura\cura_sf\skeinforge_application\skeinforge_plugins\craft_plugins\raft.py", line 236, in getCraftedTextFromText
    return RaftSkein().getCraftedGcode(gcodeText, repository)
  File "C:\Program Files (x86)\Cura_RC3\Cura\cura_sf\skeinforge_application\skeinforge_plugins\craft_plugins\raft.py", line 826, in getCraftedGcode
    self.addRaft()
  File "C:\Program Files (x86)\Cura_RC3\Cura\cura_sf\skeinforge_application\skeinforge_plugins\craft_plugins\raft.py", line 603, in addRaft
    outsetSeparateLoops = intercircle.getInsetSeparateLoopsFromLoops(self.boundaryLayers[0].loops, -self.raftOutsetRadius, 0.8)
IndexError: list index out of range

**Comment by daid** [comment]
This seems to happen because your model is thinner then the initial layer. Even if this error did not happen (fixed the error) your resulting GCode file is empty.
