### ISSUE TITLE
Cura 12.07 Project Planner - can't save combined STL files

### ISSUE THREAD

**Issue by rmccaskill** [daid/LegacyCura#175]
In Cura 12.07, when I click the  'Save all the combined STL files into a single STL file as a plate.' button (7th button) in the toolbar, the 'Save as STL dialog appears'. After entering a file name and clicking 'save', the dialog disappears and nothing is saved. The following error appears in the console:

Traceback (most recent call last):
  File "C:\Ultimaker\Cura_12.07\Cura\gui\toolbarUtil.py", line 204, in OnButton
    self.callback(event)
  File "C:\Ultimaker\Cura_12.07\Cura\gui\projectPlanner.py", line 312, in OnSave
CombinedSTL
    self._saveCombinedSTL(dlg.GetPath())
TypeError: _saveCombinedSTL() takes exactly 1 argument (2 given)

**Comment by rmccaskill** [comment]
Comment from Daid.

On Monday, 16 July 2012 11:39:06 UTC-3, Daid wrote:

```
Ah, simple bug. Missed that one during testing.

Line 315 of projectPlanner.py should be: "def _saveCombinedSTL(self, filename):" instead of "def _saveCombinedSTL(filename):" I've fixed it for the next release.
```
