### ISSUE TITLE
Rerun first run wizard crashes on mac

### ISSUE THREAD

**Issue by fuegas** [daid/LegacyCura#197]
In the normal mode I pressed "ReRun first run wizard", which gave the following error:

Traceback (most recent call last):
  File "/Users/X/Documents/GitHub/Cura/Cura/gui/mainWindow.py", line 336, in OnFirstRunWizardconfigWizard.configWizard()
  File "/Users/X/Documents/GitHub/Cura/Cura/gui/configWizard.py", line 496, in **init**
    self.firstInfoPage = FirstInfoPage(self)
  File "/Users/X/Documents/GitHub/Cura/Cura/gui/configWizard.py", line 98, in **init**
    super(FirstInfoPage, self).**init**(parent, "First time run wizard")
  File "/Users/X/Documents/GitHub/Cura/Cura/gui/configWizard.py", line 18, in **init**
    sizer.AddGrowableCol(1)
  File "/usr/local/lib/wxPython-2.9.3.1/lib/python2.7/site-packages/wx-2.9.3-osx_cocoa/wx/_core.py", line 15372, in AddGrowableCol
    return _core_.FlexGridSizer_AddGrowableCol(_args, *_kwargs)
wx._core.PyAssertionError: C++ assertion "!m_cols || idx < (size_t)m_cols" failed at /BUILD/wxPython-src-2.9.3.1/src/common/sizer.cpp(1956) in AddGrowableCol(): invalid column index

**Comment by daid** [comment]
Py, if you remove the preferences.ini file and restart Cura, do you get the same error? (This should start the first run wizard)

**Comment by daid** [comment]
Does this still happen with the latest development version? (there was a bug in the wizard at that time)

**Comment by fuegas** [comment]
Yeah, crashes with latest dev version
