### ISSUE TITLE
Serial connection fails

### ISSUE THREAD

**Issue by diara628** [daid/LegacyCura#20]
I have an Ultimaker with the newer electronics. I updated the firmware with the wizard, but now connecting fails during sanity checks:

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in **bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/drayko/RepRap/linux-SkeinPyPy-NewUI-Beta4/SkeinPyPy/newui/configWizard.py", line 175, in OnRun
    self.comm = machineCom.MachineCom()
  File "/home/drayko/RepRap/linux-SkeinPyPy-NewUI-Beta4/SkeinPyPy/newui/machineCom.py", line 110, in __init**
    self.serial = Serial(port, baudrate, timeout=5)
  File "/usr/local/lib/python2.7/dist-packages/pyserial-2.6-py2.7.egg/serial/serialutil.py", line 261, in **init**
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/pyserial-2.6-py2.7.egg/serial/serialposix.py", line 282, in open
    self._reconfigurePort()
  File "/usr/local/lib/python2.7/dist-packages/pyserial-2.6-py2.7.egg/serial/serialposix.py", line 417, in _reconfigurePort
    set_special_baudrate(self, custom_baud)
  File "/usr/local/lib/python2.7/dist-packages/pyserial-2.6-py2.7.egg/serial/serialposix.py", line 47, in set_special_baudrate
    FCNTL.ioctl(port.fd, TERMIOS.TIOCGSERIAL, buf)
IOError: [Errno 22] Invalid argument

This is with both beta4 and latest from git, pyserial 2.5 and 2.6

Pronterface fails with the same error. Seems that pyserial doesn't like the baudrate argument, lower baudrates (in pronterface) seem to work (fails later).

**Comment by daid** [comment]
Looks like your kernel/USB-Serial driver doesn't seem to accept 250000 baud, which is kind of a none-standard baudrate.
Maybe you have an older kernel?

Anyhow, if you just want it to work, build a custom firmware with http://daid.mine.nu/~daid/marlin_build/ with a baudrate that works. Download the hex file, and use the advanced menu "Install custom firmware" to install it.

I've also pushed a change that hopefully caches this error, and handles it a bit more gracefully.

**Comment by diara628** [comment]
Yes, that, or the hardware doesn't like it. I'm using the latest Ubuntu, so the latter seems more propable. I did build myself a marlin with a baudrate of 115200, and it seems to work. Now, the appropriate thing to do is the enable SkeinPypy to use different baudrates (115200 seems widely used/supported) in the wizard.

**Comment by diara628** [comment]
Also, are the build-me-marlin defaults the same as what comes with SkeinPypy, and are they optimal? At least the M109 wait time should be less than 30 seconds.

**Comment by daid** [comment]
A baudrate of 250000 yields less communication errors for some reason (no idea why, but people have tested it)
It also gives more bandwidth to play with, which is important on high detailed prints. So you don't get buffer underruns.

The latest github version uses the baudrate configured in the preferences for the wizard. It's a bit sub-optimal that you have to close down the wizard, change the baudrate, and re-run the wizard. But 80-90% of the users will never encounter this problem.

**Comment by daid** [comment]
The 12.07 release installs a 115200 baudrate firmware by default if you run linux. There is also the auto-baudrate detection and some extra exception handling in the code so this problem is handled more gracefully.
