### ISSUE TITLE
can't slice ERROR

### ISSUE THREAD

**Issue by MaurinElectroTextile** [daid/LegacyCura#208]
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in **bootstrap_inner
    self.run()
  File "/home/maurin/Applications/linux-Cura-12.08/Cura/gui/sliceProgessPanel.py", line 138, in run
    p = subprocess.Popen(self.cmdList[self.fileIdx], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file...

**Comment by daid** [comment]
Most likely you are running Cura on a 64bit only system, which means you have to replace the supplied PyPy with the 64bit version.

**Comment by MaurinElectroTextile** [comment]
ok, suppress the pypy folder fix the bug! :-)
thx daid.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
