### ISSUE TITLE
Unable to switch between model views on Mac.

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#25]
The combo box for switching between mode views (e.g. Model – Normal, GCode, etc.) does not work on the Mac. You can select a different view from the combo box but the preview window does not change.

The "Show result" button for a slice does switch to GCode view, but then there's no way to switch back to viewing the STL or any other view.

This has been broken since you added the combo box but I just got around to filing it.

Also when you slice a file it does not automatically switch to the GCode view (a feature I think you added recently). It remains on the Model - Normal view until you click the "Show result" button.

**Comment by daid** [comment]
Great that you're testing new features :)

The last part is indeed true, that's also true for Windows/Linux.

For the other part, I'll have to investigate why it doesn't work. Does enabling support work? (as that uses the same type of combobox)

**Comment by RedwoodForest** [comment]
So I tried to enable support ("Everywhere") and got the stack trace below.

The more worrying thing is that even after changing support back to "None" everything I try to slice still fails with the same issue.

Traceback (most recent call last):
  File "app_main.py", line 51, in run_toplevel
  File "/Applications/SkeinPyPy/SkeinPyPy/skeinpypy.py", line 58, in <module>
    main()
  File "/Applications/SkeinPyPy/SkeinPyPy/skeinpypy.py", line 53, in main
    skeinRun.runSkein(args)
  File "/Applications/SkeinPyPy/SkeinPyPy/newui/skeinRun.py", line 31, in runSkein
    skeinforge_craft.writeOutput(fileName)
  File "/Applications/SkeinPyPy/SkeinPyPy/skeinforge_application/skeinforge_utilities/skeinforge_craft.py", line 140, in writeOutput
    return pluginModule.writeOutput(fileName, shouldAnalyze)
  File "/Applications/SkeinPyPy/SkeinPyPy/skeinforge_application/skeinforge_plugins/craft_plugins/export.py", line 275, in writeOutput
    gcodeText = skeinforge_craft.getChainTextFromProcedures(fileName, procedures[: -1], gcodeText)
  File "/Applications/SkeinPyPy/SkeinPyPy/skeinforge_application/skeinforge_utilities/skeinforge_craft.py", line 44, in getChainTextFromProcedures
    text = craftModule.getCraftedText(fileName, text)
  File "/Applications/SkeinPyPy/SkeinPyPy/skeinforge_application/skeinforge_plugins/craft_plugins/carve.py", line 134, in getCraftedText
    settings.getReadRepository(repository)
  File "/Applications/SkeinPyPy/SkeinPyPy/fabmetheus_utilities/settings.py", line 410, in getReadRepository
    p.setValueToString(str(info[name](p)))
  File "/Applications/SkeinPyPy/SkeinPyPy/fabmetheus_utilities/settings.py", line 561, in setValueToString
    self.value = float(value)
ValueError: empty string for float()

**Comment by RedwoodForest** [comment]
I found it — I had set rotate temporarily to 90 degrees and then deleted it completely instead of setting it back to 0. Let me re-run the test.

**Comment by RedwoodForest** [comment]
The support combo box does not work either. I tested both by slicing and confirming no support was generated and by confirming that the change was not saved after restarting SkeinPyPy.

**Comment by daid** [comment]
I've changed the event type used for combo boxes, I now use the proper event (odd that the other one worked at all for windows/linux)

The model tab is indeed missing validation (different bug), causing errors on slicing if you leave the boxes empty. It's also missing tooltips because I'm not that happy with those setting being in a tab there.

**Comment by RedwoodForest** [comment]
Confirmed fixed:).
