### ISSUE TITLE
py2app doesn't work on x86_64 OS X

### ISSUE THREAD

**Issue by bbum** [daid/LegacyCura#282]
./package.sh osx64
running py2app
error: argv-emulation is not supported for 64-bit executables
Cannot build app.

**Comment by bbum** [comment]
Forcing python to i386 via 'arch -arch i386 python setup.py py2app' doesn't seem to work, either.

**Comment by bbum** [comment]
Aha!  Specifying the specific version of python does work!

arch -32 python2.7 setup.py py2app

**Comment by bbum** [comment]
Bummer -- still running into the power module issue.

Traceback (most recent call last):
  File "/Volumes/Data/bbum/3DPrinting/Cura/scripts/darwin/dist/Cura.app/Contents/Resources/**boot**.py", line 187, in <module>
    _run('cura.py')
  File "/Volumes/Data/bbum/3DPrinting/Cura/scripts/darwin/dist/Cura.app/Contents/Resources/__boot__.py", line 184, in _run
    execfile(path, globals(), globals())
  File "/Volumes/Data/bbum/3DPrinting/Cura/scripts/darwin/dist/Cura.app/Contents/Resources/cura.py", line 109, in <module>
    main()
  File "/Volumes/Data/bbum/3DPrinting/Cura/scripts/darwin/dist/Cura.app/Contents/Resources/cura.py", line 103, in main
    mainWindowRunCallback(None)
  File "/Volumes/Data/bbum/3DPrinting/Cura/scripts/darwin/dist/Cura.app/Contents/Resources/cura.py", line 95, in mainWindowRunCallback
    from Cura.gui import mainWindow
  File "Cura/gui/mainWindow.pyo", line 17, in <module>
  File "Cura/gui/configWizard.pyo", line 12, in <module>
  File "Cura/gui/printWindow.pyo", line 10, in <module>
ImportError: No module named power
2012-12-08 16:21:40.067 Cura[6428:707] Cura Error
Segmentation fault: 11

**Comment by daid** [comment]
You need install the power module from https://github.com/GreatFruitOmsk/Power

Note that we are in the process of getting the py2app working, and thus that there is still a list of problems to fix.

**Comment by bbum** [comment]
Have you talked with Ronald Oussoren about the use of py2app?

**Comment by daid** [comment]
Who?

**Comment by bbum** [comment]
Send me an email to "bbum @ ... anything apple related ... .com" and I'll make an introduction.

Ronald took over as lead developer of PyObjC (and py2app) some years ago.  He is in your neck of the woods, IIRC.

**Comment by Kentzo** [comment]
@bbum Have you installed PyObjC 2.5 as noted in manual?

**Comment by loelkes** [comment]
OK, i passed the power error but get stuck at the following...

Running 'import ctypes, ctypes.util' in python doesn't cause any error.

Obelix-2:MacOS christian$ ./Cura
<_FuncPtr object at 0x10c142ef0>
Traceback (most recent call last):
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/__boot__.py", line 187, in <module>
    _run('cura.py')
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/__boot__.py", line 184, in _run
    execfile(path, globals(), globals())
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/cura.py", line 71, in <module>
    main()
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/cura.py", line 68, in main
    app.CuraApp(args).MainLoop()
  File "Cura/gui/app.pyo", line 28, in __init__
  File "Cura/gui/app.pyo", line 42, in afterSplashCallback
  File "Cura/gui/mainWindow.pyo", line 16, in <module>
  File "Cura/gui/sceneView.pyo", line 15, in <module>
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/lib/python2.7/OpenGL/GLU/**init**.py", line 2, in <module>
    from OpenGL import platform
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/lib/python2.7/OpenGL/platform/**init**.py", line 35, in <module>
    _load()
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/lib/python2.7/OpenGL/platform/__init__.py", line 26, in _load
    plugin_class = plugin.load()
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/lib/python2.7/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/lib/python2.7/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/lib/python2.7/OpenGL/platform/darwin.py", line 24, in <module>
    import ctypes, ctypes.util
ImportError: No module named util
2013-10-14 02:42:05.170 Cura[56436:707] Cura Error
objc[56436]: autorelease pool page 0x7fe3d314d000 corrupted
  magic 0x00000000 0xf0000000 0x00000000 0xf0000000
  pthread 0x7fff712c8180

Illegal instruction: 4

**Comment by bbum** [comment]
Ronald,

```
Can you give some advice on building Cura 64 bit?

thanks,
b.bum
```

**Comment by loelkes** [comment]
I slept over it and reinstalled py2app (it was only compiled for i386...) with easy_install. Then everything went as expected. 

Now Cura crashes after the setup assistant with following:

Obelix-2:MacOS christian$ ./Cura
2013-10-14 08:18:42.394 Cura[58932:707] GLUT Warning: glutInit being called a second time.
Traceback (most recent call last):
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/**boot**.py", line 338, in <module>
    _run()
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/__boot__.py", line 333, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/cura.py", line 71, in <module>
    main()
  File "/Volumes/Cura - Ultimaker/Cura/Cura.app/Contents/Resources/cura.py", line 68, in main
    app.CuraApp(args).MainLoop()
  File "Cura/gui/app.pyo", line 28, in __init__
  File "Cura/gui/app.pyo", line 91, in afterSplashCallback
  File "Cura/gui/mainWindow.pyo", line 131, in **init**
  File "Cura/gui/mainWindow.pyo", line 388, in updateMachineMenu
  File "wx/_core.pyo", line 12019, in Append
wx._core.PyAssertionError: C++ assertion "id != 0 || pSubMenu != NULL" failed at /BUILD/wxPython-src-2.9.4.0/src/osx/menuitem_osx.cpp(40) in wxMenuItem(): A MenuItem ID of Zero does not work under Mac
2013-10-14 08:19:04.087 Cura[58932:707] Cura Error
objc[58932]: autorelease pool page 0x102883000 corrupted
  magic 0x00000000 0xd0000000 0x00000000 0xd0000000
  pthread 0x7fff712c8180

Illegal instruction: 4

**Comment by daid** [comment]
Must be a newer wxPython causing problems. Easy to work around.

Note that the Mac build of Cura is a complex monster which will keep eating away your sanity. I'm pulling a lot of tricks to get a version that works on 10.6 or later. Note, the newer your MacOS version, the harder to build a version that works on backwards version. (Apple hates you, always remember that)

**Comment by loelkes** [comment]
That was really fast, thank you! :+1: Works!
This was on OSX 10.8.4, i will try it on my old 10.6 Laptop :-D

**Comment by Kentzo** [comment]
@loelkes If you don't need backward compatibility, you can build Cura on any further version of OSX.
If you need 10.6 compatibility, you have to build Cura on 10.7 or earlier.

**Comment by Kentzo** [comment]
@daid Maybe worth to add this to README?
