### ISSUE TITLE
Slicing failure on Mac, Cura 12.12

### ISSUE THREAD

**Issue by StanleyKnife** [daid/LegacyCura#316]
"Something went wrong during slicing!" message after every slicing attempt.

Love the new look and functionality, by the way.

Here's the log:

Traceback (most recent call last):
  File "app_main.py", line 51, in run_toplevel
  File "/Applications/Cura/Cura.app/Contents/Resources/pypy/lib-python/2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Applications/Cura/Cura.app/Contents/Resources/pypy/lib-python/2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Applications/Cura/Cura.app/Contents/Resources/Cura/cura.py", line 78, in <module>
    main()
  File "/Applications/Cura/Cura.app/Contents/Resources/Cura/cura.py", line 67, in main
    sliceRun.runSlice(args)
  File "Cura/util/sliceRun.py", line 89, in runSlice
    skeinforge_craft.writeOutput(fileName)
  File "Cura/cura_sf/skeinforge_application/skeinforge_utilities/skeinforge_craft.py", line 133, in writeOutput
    return pluginModule.writeOutput(fileName, shouldAnalyze)
  File "/Applications/Cura/Cura.app/Contents/Resources/Cura/cura_sf/skeinforge_application/skeinforge_plugins/craft_plugins/export.py", line 266, in writeOutput
    print('File ' + archive.getSummarizedFileName(fileName.encode('ascii', 'replace')) + ' is being chain exported.')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc6 in position 11: ordinal not in range(128)

**Comment by daid** [comment]
The problem is in the filename/path you are using. Most likely there is an dash on a character somewhere which is causing the problem. There where tons of problems like this in Skeinforge code, and I thought I fixed them all, but I missed one which is causing this problem is already fixed for the next release.

**Comment by daid** [comment]
See: https://github.com/daid/Cura/issues/307

**Comment by StanleyKnife** [comment]
Got it. I use the letter ƒ to denote a folder, that must be it.

Thank you!
