### ISSUE TITLE
Crash after first run wizard

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#34]
I just updated to the renamed Cura sources and attempted to run Cura.

I got through the first run wizard okay, but then I got a crash.

This is on OS X 10.7.3.

Here's the console text:
wizardDone not found in preferences, so using default: False
filament_diameter not found in profile, so using default: 2.89
steps_per_e not found in preferences, so using default: 0
startMode not found in preferences, so using default: Simple
Traceback (most recent call last):
  File "/Applications/Cura/Cura/cura.py", line 59, in <module>
    main()
  File "/Applications/Cura/Cura/cura.py", line 56, in main
    mainWindow.main()
  File "/Applications/Cura/Cura/gui/mainWindow.py", line 28, in main
    simpleMode.simpleModeWindow()
  File "/Applications/Cura/Cura/gui/simpleMode.py", line 23, in **init**
    self.SetIcon(icon.getMainIcon())
  File "/usr/local/lib/wxPython-2.9.3.1/lib/python2.7/site-packages/wx-2.9.3-osx_cocoa/wx/lib/embeddedimage.py", line 58, in GetIcon
    icon.CopyFromBitmap(self.GetBitmap())
  File "/usr/local/lib/wxPython-2.9.3.1/lib/python2.7/site-packages/wx-2.9.3-osx_cocoa/wx/_gdi.py", line 1314, in CopyFromBitmap
    return _gdi_.Icon_CopyFromBitmap(_args, *_kwargs)
wx._core.PyAssertionError: C++ assertion "err == noErr" failed at /BUILD/wxPython-src-2.9.3.1/src/osx/core/bitmap.cpp(639) in GetIconRef(): Error when constructing icon ref

**Comment by daid** [comment]
I added a window/system-tray icon yesterday. However, it didn't work for windows, as it showed on icon for windows. And it seems to crash the MacOS version. It worked on linux however... odd.

I've disabled the window icons. Should resolve this.

**Comment by RedwoodForest** [comment]
Confirmed fixed.
