### ISSUE TITLE
Cannot prepare print on linux

### ISSUE THREAD

**Issue by tbenst** [daid/LegacyCura#352]
After I click prepare print on Linux Mint 14 (Ubuntu 12.10), The processing hangs on "Starting..."

Output from terminal:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in **bootstrap_inner
    self.run()
  File "Cura/gui/sliceProgessPanel.py", line 172, in run
    p = sliceRun.startSliceCommandProcess(self.cmdList[self.fileIdx])
  File "Cura/util/sliceRun.py", line 196, in startSliceCommandProcess
    return subprocess.Popen(cmdList, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

The link below may be related to the issue:
http://stackoverflow.com/questions/9922651/python2-setting-time-error

**Comment by greenarrow** [comment]
I don't think the link is related.

Are you using a packaged release or a git checkout?
If using git have you tried a packaged release from: http://daid.github.com/Cura

**Comment by daid** [comment]
Problem is related to 64bit while Cura for linux was packaged for 32bit.

Next release will feature a .deb for Ubuntu, which solves this issue (out next week)
