### ISSUE TITLE
slicing from the command line

### ISSUE THREAD

**Issue by MrBalonio** [daid/LegacyCura#432]
/usr/bin/python /usr/share/cura/cura.py -s XYZ_nickel_Calibration_2.stl  
Traceback (most recent call last):  
  File "/usr/share/cura/cura.py", line 33, in <module>  
    cura.main()  
  File "/usr/share/cura/Cura/cura.py", line 45, in main  
    slicer = sliceEngine.Slicer()  
TypeError: **init**() takes exactly 2 arguments (1 given)

**Comment by daid** [comment]
Mmm, ok, yes. The progress bar stuff seems to have broken this. My mistake.
