### ISSUE TITLE
slicing from the command line

### ISSUE THREAD

**Issue by MrBalonio** [daid/LegacyCura#434]
I git pull the lastest version and I am getting this error when I try to slice from the command line. 
/usr/share/cura/./cura.py -s XYZ_nickel_Calibration_2.stl  
Traceback (most recent call last):  
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 151, in runSlicer  
    self._process = self._runSliceProcess(commandList)  
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 284, in _runSliceProcess  
    return subprocess.Popen(cmdList, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)  
  File "/usr/lib/python2.6/subprocess.py", line 633, in __init__  
    errread, errwrite)  
  File "/usr/lib/python2.6/subprocess.py", line 1139, in _execute_child  
    raise child_exception  
OSError: [Errno 2] No such file or directory  
Traceback (most recent call last):  
  File "/usr/share/cura/./cura.py", line 33, in <module>  
    cura.main()  
  File "/usr/share/cura/Cura/cura.py", line 54, in main  
    shutil.copyfile(slicer.getGCodeFilename(), args[0] + '.gcode')  
  File "/usr/lib/python2.6/shutil.py", line 52, in copyfile  
    fsrc = open(src, 'rb')  
IOError: [Errno 2] No such file or directory: '/tmp/Cura_bxPITx'

**Comment by daid** [comment]
The commandline slicing in that version is also broken apparently. Working on a fix.

**Comment by rishabh2809** [comment]
I am also getting the same error in commandline slicing. Is this bug fixed?

options.output =
/home/rishabh/data/mirre.gcode
Traceback (most recent call last):
  File "/home/rishabh/bin/Cura/cura.py", line 86, in <module>
    main()
  File "/home/rishabh/bin/Cura/cura.py", line 74, in main
    shutil.copyfile(slicer.getGCodeFilename(), options.output)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/tmp/Cura_SeagOa'
