### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by hroncok** [daid/LegacyCura#464]
I get several of those after Cura starts. Doesn't seem to prevent cura from working.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Cura/gui/sceneView.py", line 414, in _onRunSlicer
    self._slicer.runSlicer(self._scene)
  File "/usr/lib/python2.7/site-packages/Cura/util/sliceEngine.py", line 106, in runSlicer
    for k, v in self._engineSettings(extruderCount).iteritems():
  File "/usr/lib/python2.7/site-packages/Cura/util/sliceEngine.py", line 248, in _engineSettings
    'startCode': profile.getAlterationFileContents('start.gcode', extruderCount),
  File "/usr/lib/python2.7/site-packages/Cura/util/profile.py", line 781, in getAlterationFileContents
    return unicode(prefix + re.sub("(.)\{([^\}]*)\}", replaceTagMatch, alterationContents).rstrip() + '\n' + postfix).strip().encode('utf-8') + '\n'
  File "/usr/lib64/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python2.7/site-packages/Cura/util/profile.py", line 673, in replaceTagMatch
    return pre + time.strftime('%a').encode('utf-8', 'replace')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

Aren't you decoding soemthing you should not?

**Comment by hroncok** [comment]
Might be fixed in 595e55c6bc048d9c0233354a44ad677131c63680, will test it soon.
