### ISSUE TITLE
Cura 13.6.4 UnicodeDecodeError on Mac 10.8.4

### ISSUE THREAD

**Issue by jimaobian** [daid/LegacyCura#487]
I run the Cura in terminal. An error exists.

Traceback (most recent call last):
  File "Cura/gui/sceneView.pyo", line 419, in _onRunSlicer
  File "Cura/util/sliceEngine.pyo", line 112, in runSlicer
  File "Cura/util/sliceEngine.pyo", line 255, in _engineSettings
  File "Cura/util/profile.pyo", line 793, in getAlterationFileContents
  File "re.pyo", line 151, in sub
  File "Cura/util/profile.pyo", line 685, in replaceTagMatch
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)

I'm not familiar with python. How can I deal with it?
Thank you~~

**Comment by hroncok** [comment]
Seems like Issue #464.

**Comment by jimaobian** [comment]
Change the local to England or America and this bug no longer exists. Perhaps it may be fixed in the next version~~

**Comment by daid** [comment]
I've changed some things and I hope it will be fixed in the next version because of this.
