### ISSUE TITLE
August breaks Cura slicing in countries where it is accentuated

### ISSUE THREAD

**Issue by iXce** [daid/LegacyCura#523]
Cura won't slice objects today, outputting the backtrace below. Looking at it, I guess it's because August is spelled août in French. Running with LANG=C fixes it.

I can look at fixing it myself, but it's probably trivial to fix :)

```
Traceback (most recent call last):
  File "/usr/share/cura/Cura/gui/sceneView.py", line 420, in _onRunSlicer
    self._slicer.runSlicer(self._scene)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 116, in runSlicer
    for k, v in self._engineSettings(extruderCount).iteritems():
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 259, in _engineSettings
    'startCode': profile.getAlterationFileContents('start.gcode', extruderCount),
  File "/usr/share/cura/Cura/util/profile.py", line 793, in getAlterationFileContents
    return unicode(prefix + re.sub("(.)\{([^\}]*)\}", replaceTagMatch, alterationContents).rstrip() + '\n' + postfix).strip().encode('utf-8') + '\n'
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/share/cura/Cura/util/profile.py", line 683, in replaceTagMatch
    return pre + time.strftime('%d %b %Y').encode('utf-8', 'replace')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/share/cura/Cura/gui/sceneView.py", line 420, in _onRunSlicer
    self._slicer.runSlicer(self._scene)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 116, in runSlicer
    for k, v in self._engineSettings(extruderCount).iteritems():
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 259, in _engineSettings
    'startCode': profile.getAlterationFileContents('start.gcode', extruderCount),
  File "/usr/share/cura/Cura/util/profile.py", line 793, in getAlterationFileContents
    return unicode(prefix + re.sub("(.)\{([^\}]*)\}", replaceTagMatch, alterationContents).rstrip() + '\n' + postfix).strip().encode('utf-8') + '\n'
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/share/cura/Cura/util/profile.py", line 683, in replaceTagMatch
    return pre + time.strftime('%d %b %Y').encode('utf-8', 'replace')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)
```

**Comment by daid** [comment]
Yes, known problem and already fixed for the next release.

(Python is horribly mixing ascii and unicode strings, Python3 would solve it, but wxPython has not been ported to Python3 yet)

**Comment by iXce** [comment]
Ah, great. Yeah, Python2 is a pain for that :) I guess we're all waiting for wxPython-Phoenix :)
