### ISSUE TITLE
Locale problem of Cura 13.06.5

### ISSUE THREAD

**Issue by huanghy268** [daid/LegacyCura#548]
Can't create gcode on linux mint 15 64 bit, locale is zh_CN.UTF-8. I change locale to LC_ALL=C, it can work. 

console output on locale zh_CN.UTF-8

Traceback (most recent call last):
  File "/usr/share/cura/Cura/gui/sceneView.py", line 420, in _onRunSlicer
    self._slicer.runSlicer(self._scene)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 116, in runSlicer
    for k, v in self._engineSettings(extruderCount).iteritems():
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 259, in _engineSettings
    'startCode': profile.getAlterationFileContents('start.gcode', extruderCount),
  File "/usr/share/cura/Cura/util/profile.py", line 793, in getAlterationFileContents
    return unicode(prefix + re.sub("(.){([^}]_)}", replaceTagMatch, alterationContents).rstrip() + '\n' + postfix).strip().encode('utf-8') + '\n'
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/share/cura/Cura/util/profile.py", line 685, in replaceTagMatch
    return pre + time.strftime('%a').encode('utf-8', 'replace')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/share/cura/Cura/gui/sceneView.py", line 420, in _onRunSlicer
    self._slicer.runSlicer(self._scene)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 116, in runSlicer
    for k, v in self._engineSettings(extruderCount).iteritems():
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 259, in _engineSettings
    'startCode': profile.getAlterationFileContents('start.gcode', extruderCount),
  File "/usr/share/cura/Cura/util/profile.py", line 793, in getAlterationFileContents
    return unicode(prefix + re.sub("(.){([^}]_)}", replaceTagMatch, alterationContents).rstrip() + '\n' + postfix).strip().encode('utf-8') + '\n'
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/share/cura/Cura/util/profile.py", line 685, in replaceTagMatch
    return pre + time.strftime('%a').encode('utf-8', 'replace')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

**Comment by shellixyz** [comment]
I noticed the same problem with Debian and Fedora 19

**Comment by daid** [comment]
Known problem, fix is in place for the next release. A workaround is removing the {date} and {day} tags from the start.gcode.
