### ISSUE TITLE
Cura 13.10 slicing doesn't work on debian

### ISSUE THREAD

**Issue by MaurinElectroTextile** [daid/LegacyCura#583]
I did the installation following te readme instructions.
Cura is working but I can't sclice my stl.

Console message ERROR :

Traceback (most recent call last):
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 178, in _watchProcess
    self._process = self._runSliceProcess(commandList)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 333, in _runSliceProcess
    return subprocess.Popen(cmdList, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] Aucun fichier ou dossier de ce type

**Comment by daid** [comment]
Guess you are missing a compiled engine, the ReadMe is incomplete in this area.
