### ISSUE TITLE
13.10 not slicing on OSX 10.8.4

### ISSUE THREAD

**Issue by loelkes** [daid/LegacyCura#587]
Hi
after passing issue 282 i get the following:

System is OSX 10.8.4 with python27-apple. I tried running it with non-system python but it failed until now.

Obelix-2:MacOS christian$ ./Cura
2013-10-14 12:38:41.449 Cura[60679:707] GLUT Warning: glutInit being called a second time.
Traceback (most recent call last):
  File "Cura/util/sliceEngine.pyo", line 178, in _watchProcess
  File "Cura/util/sliceEngine.pyo", line 333, in _runSliceProcess
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 679, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1228, in _execute_child
OSError: [Errno 2] No such file or directory

**Comment by daid** [comment]
Happens if no compiled engine is found. Normally the package.sh script should clone the code and build this for you.

**Comment by loelkes** [comment]
OK i had a fresh start and now everything works... must have done something wrong this morning :-0
Thank you!
