### ISSUE TITLE
Command Line Cura: "No such file or directory"

### ISSUE THREAD

**Issue by kempermo** [daid/LegacyCura#600]
I'm experimenting with Cura and the command line possibilities. When I call:

```
$ /Applications/Cura/Cura.app/Contents/MacOS/Cura -i /Applications/Cura/test.ini -s /(...Path to STL)/GiveAway.stl -o /(...Path to save GCode)/test.gcode
Traceback (most recent call last):
  File "/Applications/Cura/Cura.app/Contents/Resources/__boot__.py", line 316, in <module>
    _run()
  File "/Applications/Cura/Cura.app/Contents/Resources/__boot__.py", line 311, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Applications/Cura/Cura.app/Contents/Resources/cura.py", line 71, in <module>
    main()
  File "/Applications/Cura/Cura.app/Contents/Resources/cura.py", line 59, in main
    shutil.copyfile(slicer.getGCodeFilename(), options.output)
  File "shutil.pyo", line 82, in copyfile
IOError: [Errno 2] No such file or directory: '/var/tmp/Cura_TmpKdmSDr'
2013-10-28 10:01:24.708 Cura[2354:707] Cura Error 
```

It seems, that the engine is looking for a temp folder. I was just curious and found out, that the naming is different. In my '/var/tmp/' i find a file called 'Cura_TmpSsIKfO' vs. 'Cura_TmpKdmSDr' in the traceback?!

Is this a known issue? Thanks ;-)

**Comment by nallath** [comment]
What OS did you use for this? Please see; https://github.com/daid/Cura/wiki/Issue-policies
