### ISSUE TITLE
Hangs at splash screen

### ISSUE THREAD

**Issue by ambrop72** [daid/LegacyCura#655]
Cura fails to start on my system (Gentoo Linux, x86_64), hanging at the splash screen. The following exception occurs:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/wx-2.9.4-gtk2/wx/_core.py", line 16772, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/ambro/reprap/Cura/Cura/gui/splashScreen.py", line 16, in DoCallback
    self.callback()
  File "/home/ambro/reprap/Cura/Cura/gui/app.py", line 120, in afterSplashCallback
    self.mainWindow = mainWindow.mainWindow()
  File "/home/ambro/reprap/Cura/Cura/gui/mainWindow.py", line 185, in __init__
    self.scene = sceneView.SceneView(self.rightPane)
  File "/home/ambro/reprap/Cura/Cura/gui/sceneView.py", line 126, in __init__
    self.updateProfileToControls()
  File "/home/ambro/reprap/Cura/Cura/gui/sceneView.py", line 629, in updateProfileToControls
    self.sceneUpdated()
  File "/home/ambro/reprap/Cura/Cura/gui/sceneView.py", line 514, in sceneUpdated
    self._scene.updateSizeOffsets()
  File "/home/ambro/reprap/Cura/Cura/util/objectScene.py", line 120, in updateSizeOffsets
    extends.append(polygon.minkowskiHull(extends[n-1], headOffset))
  File "/home/ambro/reprap/Cura/Cura/util/polygon.py", line 48, in minkowskiHull
    return convexHull(points.copy())
  File "/home/ambro/reprap/Cura/Cura/util/polygon.py", line 23, in convexHull
    upper = [points[0], points[1]]
IndexError: list index out of range
```

 This is a regression. I've tried bisecting but there was interference from another regression. So, the results are:
- It works until 16c67477c32e8c5cdff79d23347b0713e32ee1a3, which causes the unrelation regression. That is, it will start, but display an error message "An error has occurred during the 3D view drawing. AssertionError: '/home/ambro/reprap/Cura/Cura/resources/images/checkerboard.png is not a file.'".
- That error keeps happening until ec6fb3f346b24a55c1a99dcde0132e76e1cf4b1c, after which the error described in this issue starts happening.

It's worth noting that when it worked there was no splash screen, at least one that I could see. I was also getting this (apparently harmless) error:

```
Traceback (most recent call last):
  File "/home/ambro/reprap/Cura/Cura/gui/sceneView.py", line 519, in _onRunSlicer
    self._slicer.runSlicer(self._scene)
  File "/home/ambro/reprap/Cura/Cura/util/sliceEngine.py", line 148, in runSlicer
    pos += (objMin + objMax) / 2.0 * 1000
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```

**Comment by daid** [comment]
(The harmless error should be gone in the latest commit)

**Comment by daid** [comment]
Also, running the TOT version of Cura is always a bit of a risk. I push quite often, which does not always guarantee that the TOT is in a working state.

**Comment by ambrop72** [comment]
Thanks. Though I can't reproduce the original bug any more, in any commit. Could have something to do with configuration. However, I've noticed that if I do a new start after removing ~/.cura, the first time, after the wizard is completed, it will lock up, with this error:

```
ra/power-1.2 python2.7 /home/ambro/reprap/Cura/Cura/cura.py
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/wx-2.9.4-gtk2/wx/_core.py", line 16772, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/ambro/reprap/Cura/Cura/gui/splashScreen.py", line 17, in DoCallback
    self.Destroy()
  File "/usr/lib64/python2.7/site-packages/wx-2.9.4-gtk2/wx/_core.py", line 16717, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
wx._core.PyDeadObjectError: The C++ part of the splashScreen object has been deleted, attribute access no longer allowed.
```

If after that I kill the process and start again, it starts with no errors.

**Comment by daid** [comment]
I have managed to reproduce this. And fixed up some code related to it. Hope it stays gone for everyone.

**Comment by JordanMajd** [comment]
I'm running x86_64 Arch Linux, building from the AUR and receiving the folowing error: 

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 16762, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/share/cura/Cura/gui/splashScreen.py", line 15, in DoCallback
    self.callback()
  File "/usr/share/cura/Cura/gui/app.py", line 151, in afterSplashCallback
    self.splash.Show(False)
  File "/usr/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 16707, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
wx._core.PyDeadObjectError: The C++ part of the splashScreen object has been deleted, attribute access no longer allowed.
