### ISSUE TITLE
Cura fails to start after splash screen on Thinkpad T41 with WinXP

### ISSUE THREAD

**Issue by bitbooster** [daid/LegacyCura#741]
I have an old Thinkpad T41 freshly reinstalled with Win XP that I would like to dedicate for some 3d printing tasks (I can already run Cura successfully on a Dell laptop also with XP)
I installed there Cura 14.01 (and later tried also 13.06.4), but I'm not able to get it working beyond the seeing the initial splash screen.
After a run, this is the content of the output.txt file:

Traceback (most recent call last):
  File "C:\Program Files\Cura_14.01\python\lib\site-packages\wx-2.8-msw-unicode\wx_core.py", line 14660, in <lambda>
    lambda event: event.callable(_event.args, *_event.kw) )
  File "Cura\gui\splashScreen.py", line 16, in DoCallback
    self.callback()
  File "Cura\gui\app.py", line 75, in afterSplashCallback
    from Cura.gui import mainWindow
  File "Cura\gui\mainWindow.py", line 16, in <module>
    from Cura.gui import sceneView
  File "Cura\gui\sceneView.py", line 15, in <module>
    from OpenGL.GLU import *
  File "C:\Program Files\Cura_14.01\python\lib\OpenGL\GLU__init__.py", line 4, in <module>
    from OpenGL.raw.GLU import *
  File "C:\Program Files\Cura_14.01\python\lib\OpenGL\raw\GLU__init__.py", line 6, in <module>
    from OpenGL.raw.GLU.constants import *
  File "C:\Program Files\Cura_14.01\python\lib\OpenGL\raw\GLU\constants.py", line 7, in <module>
    from OpenGL import platform, arrays
  File "C:\Program Files\Cura_14.01\python\lib\OpenGL\arrays__init__.py", line 22, in <module>
    formathandler.FormatHandler.loadAll()
  File "C:\Program Files\Cura_14.01\python\lib\OpenGL\arrays\formathandler.py", line 37, in loadAll
    cls.loadPlugin( entrypoint )
  File "C:\Program Files\Cura_14.01\python\lib\OpenGL\arrays\formathandler.py", line 44, in loadPlugin
    plugin_class = entrypoint.load()
  File "C:\Program Files\Cura_14.01\python\lib\OpenGL\plugins.py", line 14, in load
    return importByName( self.import_path )
  File "C:\Program Files\Cura_14.01\python\lib\OpenGL\plugins.py", line 28, in importByName
    module = **import**( ".".join(moduleName), {}, {}, moduleName)
  File "C:\Program Files\Cura_14.01\python\lib\OpenGL\arrays\numeric.py", line 13, in <module>
    import Numeric
  File "C:\Program Files\Cura_14.01\python\lib\OpenGL\arrays\Numeric.py", line 24, in <module>
    class NumericHandler( formathandler.FormatHandler ):
  File "C:\Program Files\Cura_14.01\python\lib\OpenGL\arrays\Numeric.py", line 26, in NumericHandler
    HANDLED_TYPES = (Numeric.ArrayType, )
AttributeError: 'module' object has no attribute 'ArrayType'

I'm sure it's an issue on my side, but... why the error? Some driver/other requirement missing?

Thanks in advance

**Comment by daid** [comment]
Cura requires working OpenGL drivers, and fails in unexpected ways during startup if those drivers are not found.
