### ISSUE TITLE
Error slicing file (unable to encode unicode char > 128 as ascii)

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#75]
Let me know if you need more information.

Traceback (most recent call last):
  File "app_main.py", line 51, in run_toplevel
  File "/Applications/Cura/Cura/cura.py", line 70, in <module>
    main()
  File "/Applications/Cura/Cura/cura.py", line 64, in main
    sliceRun.runSlice(args)
  File "/Applications/Cura/Cura/util/sliceRun.py", line 51, in runSlice
    skeinforge_craft.writeOutput(fileName)
  File "/Applications/Cura/Cura/cura_sf/skeinforge_application/skeinforge_utilities/skeinforge_craft.py", line 135, in writeOutput
    return pluginModule.writeOutput(fileName, shouldAnalyze)
  File "/Applications/Cura/Cura/cura_sf/skeinforge_application/skeinforge_plugins/craft_plugins/export.py", line 275, in writeOutput
    gcodeText = skeinforge_craft.getChainTextFromProcedures(fileName, procedures[: -1], gcodeText)
  File "/Applications/Cura/Cura/cura_sf/skeinforge_application/skeinforge_utilities/skeinforge_craft.py", line 44, in getChainTextFromProcedures
    text = craftModule.getCraftedText(fileName, text)
  File "/Applications/Cura/Cura/cura_sf/skeinforge_application/skeinforge_plugins/craft_plugins/alteration.py", line 96, in getCraftedText
    return getCraftedTextFromText(archive.getTextIfEmpty(fileName, text), repository)
  File "/Applications/Cura/Cura/cura_sf/skeinforge_application/skeinforge_plugins/craft_plugins/alteration.py", line 106, in getCraftedTextFromText
    return AlterationSkein().getCraftedGcode(gcodeText, repository)
  File "/Applications/Cura/Cura/cura_sf/skeinforge_application/skeinforge_plugins/craft_plugins/alteration.py", line 181, in getCraftedGcode
    self.addFromUpperLowerFile(repository.nameOfStartFile.value) # Add a start file if it exists.
  File "/Applications/Cura/Cura/cura_sf/skeinforge_application/skeinforge_plugins/craft_plugins/alteration.py", line 174, in addFromUpperLowerFile
    self.distanceFeedRate.addLinesSetAbsoluteDistanceMode(alterationFileLines)
  File "/Applications/Cura/Cura/cura_sf/fabmetheus_utilities/gcodec.py", line 357, in addLinesSetAbsoluteDistanceMode
    self.addLine('(<alterationDeleteThisPrefix/>)' + line)
  File "/Applications/Cura/Cura/cura_sf/fabmetheus_utilities/gcodec.py", line 326, in addLine
    self.output.write(line + '\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 55: ordinal not in range(128)

**Comment by RedwoodForest** [comment]
Have some more info for you on this one.

This happened because OS X will auto replace "..." with unicode char 2026 (horizontal ellipse) in certain situations, and this happened in my start.gcode ("..." is part of the default start.gcode). Once I changed the start.gcode back to use three periods the error no longer occurs.
