### ISSUE TITLE
Slice Engine fails to start / connect

### ISSUE THREAD

**Issue by art103** [daid/LegacyCura#792]
Using Linux Mint (64 bit) with v14.03 update, the slicer engine fails to accept a connection. 
This means that slicing does not happen and the progress bar stays at 0%.
The 13.11.2 release is OK. 

Console log below:
~ $ cura 
load preferences from /home/user/.cura/14.03/preferences.ini
Listening for engine communications on 49674
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 204, in _socketListenThread
    sock, _ = self._serversocket.accept()
  File "/usr/lib/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 4] Interrupted system call

~ $ python --version
Python 2.7.4

**Comment by art103** [comment]
Pull request sent for fix:
https://github.com/daid/Cura/pull/793
