### ISSUE TITLE
Top of tree failing on osx64

### ISSUE THREAD

**Issue by bbum** [daid/LegacyCura#80]
- package.sh osx64
- cura.sh
- run through setup, clicking "skip/cancel/continue" to get to the interface asap

Barfs here:

Traceback (most recent call last):
  File "./Cura/cura.py", line 70, in <module>
    main()
  File "./Cura/cura.py", line 67, in main
    mainWindow.main()
  File "/Volumes/Data/bbum/Desktop/Cura/osx64-Cura-RC2/Cura/gui/mainWindow.py", line 28, in main
    simpleMode.simpleModeWindow()
  File "/Volumes/Data/bbum/Desktop/Cura/osx64-Cura-RC2/Cura/gui/simpleMode.py", line 120, in **init**
    self.preview3d.loadModelFile(self.filename)
AttributeError: 'previewPanel' object has no attribute 'loadModelFile'

**Comment by berkes** [comment]
I can confirm that PyroMani's pull-request fixes the issue on Ubuntu/Linux too.

**Comment by daid** [comment]
My updates for dual extrusion have not been added to the quick print window. Which was causing this problem.
