### ISSUE TITLE
Allow cura to run on Tails

### ISSUE THREAD

**Issue by ioerror** [daid/LegacyCura#909]
I've been trying to run Cura on Tails but found that I had a syntax error:

```
amnesia@amnesia:~/$ cura 
load preferences from /home/amnesia/.cura/14.07/preferences.ini
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14614, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/share/cura/Cura/gui/splashScreen.py", line 15, in DoCallback
    self.callback()
  File "/usr/share/cura/Cura/gui/app.py", line 99, in afterSplashCallback
    from Cura.gui import mainWindow
  File "/usr/share/cura/Cura/gui/mainWindow.py", line 22, in <module>
    from Cura.gui.tools import minecraftImport
  File "/usr/share/cura/Cura/gui/tools/minecraftImport.py", line 14, in <module>
    from Cura.util.pymclevel import mclevel
  File "/usr/share/cura/Cura/util/pymclevel/__init__.py", line 2, in <module>
    from entity import Entity, TileEntity
  File "/usr/share/cura/Cura/util/pymclevel/entity.py", line 8, in <module>
    import nbt
  File "/usr/share/cura/Cura/util/pymclevel/nbt.py", line 492
    tag_classes = { c.tagID: c for c in (TAG_Byte, TAG_Short, TAG_Int, TAG_Long, TAG_Float, TAG_Double, TAG_String, TAG_Byte_Array, TAG_List, TAG_Compound, TAG_Int_Array, TAG_Short_Array) }
                                 ^
SyntaxError: invalid syntax
```

This patch allows Cura to run without issue:

```
diff --git a/Cura/util/pymclevel/nbt.py b/Cura/util/pymclevel/nbt.py
index 3e76dad..8ecc41a 100644
--- a/Cura/util/pymclevel/nbt.py
+++ b/Cura/util/pymclevel/nbt.py
@@ -487,8 +487,8 @@ class TAG_List(TAG_Value, collections.MutableSequence):
         self.value.insert(index, value)


-tag_classes = { c.tagID: c for c in (TAG_Byte, TAG_Short, TAG_Int, TAG_Long, TAG_Float, TAG_Double, TAG_String,
-    TAG_Byte_Array, TAG_List, TAG_Compound, TAG_Int_Array, TAG_Short_Array) }
+tag_classes = dict (( c.tagID, c) for c in (TAG_Byte, TAG_Short, TAG_Int, TAG_Long, TAG_Float, TAG_Double, TAG_String,
+    TAG_Byte_Array, TAG_List, TAG_Compound, TAG_Int_Array, TAG_Short_Array) )
```

**Comment by daid** [comment]
Cura needs a minimal version python version of 2.7, even with this patch stuff will break in the future.
