### ISSUE TITLE
Save issue

### ISSUE THREAD

**Issue by billout25** [daid/LegacyCura#949]
Dear All,
I have an issue, when I want to save a big model, Cura don't want save the Gcode, I need to change the resolution of modele with less layer or etc... to decrease the size of the file (approx less 150'000 Mo).
It's possible to increase this value?
Thanks
Billout25

**Comment by izo0o** [comment]
same issue for me,
can't save the gcode of a high def model in 0.02

**Comment by daid** [comment]
Most likely this is an out-of-memory issue, is this on Windows or MacOS?

**Comment by billout25** [comment]
Hi, it's on Windows 7, 64
config:
Intel core i7 - 2960XM CPU @ 2.70GHz + 16 Go of RAM
virtual memory = 16Go
Thanks

**Comment by izo0o** [comment]
windows 7, 64
core i7-4770k @ 3.5 ghz + 32 ram

memory never used more than 15 %

**Comment by daid** [comment]
Cura is a 32bit application, so it can only fully use 3GB of ram. Can you see how much ram "python.exe" is using when this failure happens?

**Comment by norpchen** [comment]
I'm having this issue right now  (win7 x64 24GB ram, Cura 14.09 and 14.07 ) -- Python.exe is using up 979,228Kb with a peak working set size of 1,196,944K and a commit size of 982,664K  

Slicing completes, but save gcode does not work.

So it's not the 3GB limit, but possibly some other resource.

It does seem to be a memory exception of some sort within python: 

Reading mesh from socket with 5361660 vertexes
Loaded from disk in 3.416s
Analyzing and optimizing model...
Face counts: 1787220 -> 1783003 99.8%
Vertex counts: 5361660 -> 890230 16.6%
Size: 94.192000 131.814000 92.624000
vMin: 67.904000 46.593000 -4.000000
vMax: 162.096000 178.407000 88.624000
vMin: -47.096000 -65.907000 0.000000
vMax: 47.096000 65.907000 92.624000
Matrix: 1.000000 0.000000 0.000000
Matrix: 0.000000 1.000000 0.000000
Matrix: 0.000000 0.000000 1.000000
Optimize model 5.305s
Slicing model...
Layer count: 1156
Exception in thread Thread-19:
Traceback (most recent call last):
  File "C:\PROGRAM FILES (X86)\CURA_14.09\PYTHON\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\PROGRAM FILES (X86)\CURA_14.09\PYTHON\lib\threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "Cura\gui\sceneView.py", line 318, in _saveGCode
    data = self._engine.getResult().getGCode()
  File "Cura\util\sliceEngine.py", line 110, in getGCode
    return block0 + data[2048:]
MemoryError

Exception in thread Thread-20:
Traceback (most recent call last):
  File "C:\PROGRAM FILES (X86)\CURA_14.09\PYTHON\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\PROGRAM FILES (X86)\CURA_14.09\PYTHON\lib\threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "Cura\gui\sceneView.py", line 318, in _saveGCode
    data = self._engine.getResult().getGCode()
  File "Cura\util\sliceEngine.py", line 110, in getGCode
    return block0 + data[2048:]
MemoryError

Exception in thread Thread-21:
Traceback (most recent call last):
  File "C:\PROGRAM FILES (X86)\CURA_14.09\PYTHON\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\PROGRAM FILES (X86)\CURA_14.09\PYTHON\lib\threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "Cura\gui\sceneView.py", line 318, in _saveGCode
    data = self._engine.getResult().getGCode()
  File "Cura\util\sliceEngine.py", line 110, in getGCode
    return block0 + data[2048:]
MemoryError

**Comment by norpchen** [comment]
Same model & same profile / settings work in 14.05RC4, so it's something since then.

**Comment by billout25** [comment]
Hi,
My "python.exe" has finish the calculation at 410 000 K.
Cura propose 55 hours and 55 meter of filament.
But when I want to save the model at Gcode, Cura doesn't execute the saving (SD or HD).
No error message
I use Cura 14.07.1 RC1.
Thanks

**Comment by daid** [comment]
I looked into this a while back, and the problem is in getting big chuncks of memory. I changed the code so it uses smaller chunks, which seems to work around this problem. The 14.09.1-RC1 has this fixed as far as I know right now:
http://software.ultimaker.com/Cura_closed_beta/

**Comment by FitSkin** [comment]
I think I have the same problem. Cura does not execute saving Gcode. There is no error message.
When I reboot my Mac, I can save, but once once.
I have 16GB of RAM, looks like 9.5GB is in use.
The Cura file I am trying to save is not large ~500KB (as a gcode file)
