### ISSUE TITLE
Failed to save gcode when slicing is completed.

### ISSUE THREAD

**Issue by ghost** [daid/LegacyCura#968]
the error in the output.txt

Traceback (most recent call last):
  File "Cura\gui\sceneView.py", line 320, in _saveGCode
    size = float(len(gcode))
  File "Cura\util\bigDataStorage.py", line 47, in __len__
    data.seek(0, 2)
  File "C:\Program Files (x86)\Cura_14.09.1_RC1\python\lib\StringIO.py", line 106, in seek
    self.buf += ''.join(self.buflist)
MemoryError

**Comment by daid** [comment]
Be sure that this isn't an out of memory condition. (As that's what usually signals the MemoryError)
