### ISSUE TITLE
Crash under Ubuntu trusty

### ISSUE THREAD

**Issue by bread-on-toast** [daid/LegacyCura#979]
Hi,
My Cura crashes under Ubuntu trusty after loading an stl-file:

$ cura
load preferences from /home/andre/.cura/14.09/preferences.ini
Listening for engine communications on 49674
Traceback (most recent call last):
  File "/usr/share/cura/Cura/gui/util/openglGui.py", line 227, in _OnGuiPaint
    self.OnPaint(e)
  File "/usr/share/cura/Cura/gui/sceneView.py", line 1024, in OnPaint
    self._renderObject(obj)
  File "/usr/share/cura/Cura/gui/sceneView.py", line 1230, in _renderObject
    m.vbo.render()
  File "/usr/share/cura/Cura/gui/util/openglHelpers.py", line 200, in render
    glVertexPointer(3, GL_FLOAT, 2_3_4, c_void_p(0))
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (/tmp/pip-build-root/PyOpenGL-accelerate/src/latebind.c:989)
  File "wrapper.pyx", line 321, in OpenGL_accelerate.wrapper.Wrapper.**call** (/tmp/pip-build-root/PyOpenGL-accelerate/src/wrapper.c:6614)
  File "/usr/local/lib/python2.7/dist-packages/OpenGL/arrays/arrayhelpers.py", line 156, in **call**
    contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
  File "/usr/local/lib/python2.7/dist-packages/OpenGL/contextdata.py", line 65, in setValue
    current = storage.get( context )
TypeError: unhashable type

**Comment by BackEMF** [comment]
I have a similair issue, (64bit Cura on a Ubuntu 64 bit box)

BTW. after installing the version is still reported as 14.01 (in synaptic and also in GDebi package installer)

**Comment by daid** [comment]
(The version report is a known bug)

The crash seems to be related to PyOpenGL, as I'm doing nothing odd except for using textbook VertexBufferObjects there. What version of PyOpenGL is shipped with Trusty?

**Comment by BackEMF** [comment]
pyopengl 3.0.2-1
http://packages.ubuntu.com/source/trusty/devel/pyopengl
What Ubuntu + Cura combi is most stable?
