### ISSUE TITLE
Cura 14.10-RC3: Plugins

### ISSUE THREAD

**Issue by Salandora** [daid/LegacyCura#983]
Hello,

Today I updated to the 14.10-RC3 version of Cura and noticed that when using any Plugin, no matter which one, the Slice won't end.
After restarting with a terminal open I get the following output:

```
Exception in thread Thread-59:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/cura/Cura/util/sliceEngine.py", line 394, in _watchProcess
    pluginError = pluginInfo.runPostProcessingPlugins(self._result)
  File "/usr/share/cura/Cura/util/pluginInfo.py", line 134, in runPostProcessingPlugins
    data = gcode.read()
  File "/usr/share/cura/Cura/util/bigDataStorage.py", line 25, in read
    ret = self._active.read(size)
TypeError: an integer is required
```

Greetings
Salandora

**Comment by Salandora** [comment]
Me again sorry,

a little fix I use now is in bigDataStorage.py line 25 from:

```
def read(self, size=None):
```

to:

```
def read(self, size=16384):
```

This at least let's me slice again.

**Comment by MoonCactus** [comment]
FYI I had the same issue with 14.10-RC4 on Kubuntu.
and your fix works for me also (thanks)
